// GENERATED by build-palettes.mjs on 2026-10-07 from palettes.template.ts + palette-data.json.
// Edit those and re-run; palettes.test.mjs re-validates everything in this file.
//
// GD360 chart palettes — validated, self-contained (no imports).
//
// Every categorical palette below passes, on the product's real chart surfaces
// (light #ffffff, dark #141413), the checks of the dataviz method:
//   • lightness band      OKLCH L 0.43–0.77 light · 0.48–0.67 dark
//   • chroma floor        OKLCH C ≥ 0.10 (below it a hue reads as grey)
//   • CVD separation      adjacent slots ΔE ≥ 8 under protanopia AND deuteranopia
//   • normal-vision floor adjacent slots ΔE ≥ 15
//   • contrast            every slot ≥ 3:1 against the chart surface
// ΔE is Euclidean distance in OKLab × 100; colour-vision deficiency is simulated with
// Machado, Oliveira & Fernandes (2009) at severity 1.0 — the thresholds are calibrated to
// that model. Light and dark are separate selections of the same hues, never an inversion.
//
// Rules for using them:
//   • Assign hues in the fixed order given — slot 1, then 2 … never cycled, never re-sorted
//     by value. Colour follows the entity, not its rank.
//   • At most 10 coloured values; fold the rest into the palette's neutral `other` grey.
//   • The adjacent-pair guarantee covers bars, stacks and lines. Where any two marks can sit
//     side by side (scatter, bubbles, maps) use fewer series — see ALL_PAIRS_SAFE_SLOTS.
//   • Sequential ramps are one hue; index 0 is the LOWEST value in both modes (lightest on
//     the light surface, darkest on the dark one — nearest the surface either way).
//   • Diverging ramps are two hues around a neutral grey midpoint (index 3).
//   • STATUS colours are reserved for state and always ship with an icon + label.

export type Mode = "light" | "dark";
export type Hex7 = [string, string, string, string, string, string, string];
export type Hex10 = [string, string, string, string, string, string, string, string, string, string];

export type Palette = {
  id: string;
  name: string;
  /** one short line */
  description: string;
  /** 10 ordered hues for the light chart surface (#ffffff) */
  light: Hex10;
  /** the same 10 hues, re-stepped for the dark chart surface (#141413) */
  dark: Hex10;
  /** neutral grey for the folded "Other" bucket */
  other: { light: string; dark: string };
};

export type Ramp = { light: Hex7; dark: Hex7 };
export type StatusColors = { good: string; warning: string; serious: string; critical: string };

/** Chart surface each mode was validated against. */
export const SURFACE: Record<Mode, string> = { light: "#ffffff", dark: "#141413" };
/** Page plane behind the chart surface. */
export const PAGE: Record<Mode, string> = { light: "#f6f6f3", dark: "#0c0c0b" };

export const PALETTES: Palette[] = [
  {
    id: "gd360",
    name: "GD360",
    description: "The house palette: balanced, familiar, built around the brand's blue-and-pine pairing.",
    light: ["#3987e5","#d95926","#199e70","#c98500","#d55181","#008300","#7553cc","#854a12","#32a0bb","#7f2f7e"],
    dark: ["#3987e5","#d95926","#199e70","#c98500","#d55181","#008300","#9277e5","#9e602c","#00a5c5","#954494"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blues and teals with sand and coral accents; calm and trustworthy.",
    light: ["#1769c3","#b58c2c","#04a4a9","#ca6354","#4443b1","#399068","#009be6","#507b00","#8979bf","#006c49"],
    dark: ["#287ad9","#b88c23","#28a6aa","#d67465","#5456c8","#06a36b","#009dea","#60862d","#9485cb","#047853"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm ambers, corals and dusk purples with one teal counterweight; energetic without shouting.",
    light: ["#c26200","#8648ad","#019e9e","#85322d","#b68f05","#bf307a","#3664d1","#d57477","#7d2c6e","#8e7dd4"],
    dark: ["#cf6900","#9a57c4","#11a6a6","#a5433d","#af9040","#d1448a","#4e79db","#d57376","#914882","#9584dd"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Pine, fern and moss with bark and ochre; natural and grounded.",
    light: ["#006d49","#bd8c00","#3c7db0","#c24f1e","#049a8f","#853266","#76994e","#8b4a13","#9e75c9","#77720b"],
    dark: ["#008158","#bc8b00","#4b98d5","#ca623a","#21a79b","#a24c80","#74a237","#96531c","#a382c6","#7e7907"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "berry",
    name: "Berry",
    description: "Raspberry, grape and blueberry with leaf-green and peach relief; rich and confident.",
    light: ["#bf2074","#3362cf","#c3864f","#863fb0","#3a874f","#9b84d4","#793168","#d96171","#494395","#bd55b6"],
    dark: ["#ce4586","#4e7be1","#c57c33","#9659bd","#4d9d61","#9c81dd","#8d4c7c","#d5727c","#5d53bf","#cd65c5"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "slate",
    name: "Slate",
    description: "Muted, low-saturation tones for dense corporate reporting.",
    light: ["#30679c","#a85831","#27977a","#824b86","#ad8e41","#2a8ebd","#c26e7f","#547424","#8d8cdb","#7c3f08"],
    dark: ["#417cb7","#ba6841","#41a589","#99629d","#af9040","#459fcb","#d07486","#628137","#8785d4","#925321"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "vivid",
    name: "Vivid",
    description: "High-saturation hues for presentations and big-screen dashboards.",
    light: ["#1368e8","#c97f00","#be0f98","#00a27f","#7c28d7","#819700","#3b36bb","#e65c77","#00a0cc","#aa4a10"],
    dark: ["#3983fe","#cb8000","#c72aa1","#04ad88","#9554ee","#829900","#4d51d6","#dc6b7e","#00a3d0","#b85011"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
  {
    id: "cbsafe",
    name: "Colour-blind safe",
    description: "Okabe–Ito hues re-stepped into three lightness tiers so they stay apart for red-green colour-blind readers.",
    light: ["#004daa","#ac6304","#00a68f","#86177d","#a07dfb","#98991e","#3c80b4","#912a00","#6e50d9","#b4446b"],
    dark: ["#1163b6","#b16a0b","#39a790","#a53796","#8f81e8","#9b981b","#408bbc","#bd2900","#7153dd","#b06176"],
    other: { light: "#8f8e88", dark: "#7f7e78" },
  },
];

/** Single-hue 7-step ramp per palette id — index 0 = lowest value, index 6 = highest. */
export const SEQUENTIAL: Record<string, Ramp> = {
  gd360: {
    light: ["#78c5a1","#47b185","#169a6c","#108059","#0a6647","#054e35","#023724"],
    dark: ["#065439","#0c6e4d","#138a61","#2fa578","#65bd95","#92d4b4","#adefcf"],
  },
  ocean: {
    light: ["#6cbfe8","#2fa8dc","#158fbf","#0f769f","#095f80","#054862","#023347"],
    dark: ["#064f6b","#0c678b","#1281ac","#189ccf","#56b5e3","#88cef2","#b9e6fe"],
  },
  sunset: {
    light: ["#f6a17a","#e87f4d","#d26124","#b34b0d","#8f3b08","#6c2d0b","#4f1c01"],
    dark: ["#7d3307","#9f420a","#c3530f","#dc6e38","#ec8f64","#fab08e","#fed4c1"],
  },
  forest: {
    light: ["#82c490","#59af6f","#359953","#1d813f","#196733","#174e27","#023816"],
    dark: ["#0f5527","#0d7034","#238b46","#48a561","#72bc83","#9ad3a5","#b5efc0"],
  },
  berry: {
    light: ["#f599c5","#e674ae","#cf5596","#b13e7d","#8d3263","#6a264b","#510e35"],
    dark: ["#7b2b57","#a03570","#c04788","#d963a0","#ea85b7","#f9a8ce","#fecfe3"],
  },
  slate: {
    light: ["#92b9e1","#70a0d2","#5388be","#3f71a3","#325a82","#274462","#122f4c"],
    dark: ["#294c6e","#346391","#467bb0","#6194c8","#83aeda","#a5c7eb","#c6e1fe"],
  },
  vivid: {
    light: ["#8cb6fc","#629cfb","#397ff4","#2467d5","#1d53aa","#183f7f","#022967"],
    dark: ["#184692","#1b5ac0","#2b72e6","#4b8dfb","#78aafc","#a3c5fd","#ccdffe"],
  },
  cbsafe: {
    light: ["#7ebaf6","#53a1ed","#2d88da","#1370bc","#125996","#124471","#012f55"],
    dark: ["#0c4b81","#0b62a8","#1c7bcb","#4194e4","#6caff2","#96c8fd","#c6e1fe"],
  },
};

/** Two-hue 7-step ramp per palette id — [−3, −2, −1, neutral, +1, +2, +3]. */
export const DIVERGING: Record<string, Ramp> = {
  gd360: {
    light: ["#125aa8","#4e8bd7","#94bef3","#eeede9","#eca890","#ca6a48","#993508"],
    dark: ["#a9cefd","#609eeb","#4a71a1","#3a3a37","#9a5c46","#df7d5a","#f8baa5"],
  },
  ocean: {
    light: ["#0b6677","#1799b1","#7fc8d9","#eeede9","#e7a999","#c1705c","#81493b"],
    dark: ["#86d9ee","#24adc8","#2f7a8b","#3a3a37","#965e50","#d8806a","#fdb7a5"],
  },
  sunset: {
    light: ["#644b8d","#9577c8","#c2afe8","#eeede9","#e2ae85","#be7531","#854a08"],
    dark: ["#d3befd","#a789dc","#766398","#3a3a37","#92633b","#d28845","#f6bd8f"],
  },
  forest: {
    light: ["#864816","#b7784d","#ddb092","#eeede9","#94c1e1","#4c91bf","#0a618f"],
    dark: ["#f7bc95","#cb8b5e","#8d6449","#3a3a37","#4a7491","#5ea3d2","#97d3fd"],
  },
  berry: {
    light: ["#436709","#709842","#a9c68d","#eeede9","#cbace3","#a073c0","#70448d"],
    dark: ["#b4d891","#82aa55","#5f7844","#3a3a37","#7d6193","#b385d4","#dfb8fd"],
  },
  slate: {
    light: ["#215d96","#5e8dbe","#9ebee1","#eeede9","#ddaf9b","#b7775b","#8c431f"],
    dark: ["#a3cffd","#6fa0d1","#547291","#3a3a37","#8d6451","#ca896c","#f7bba0"],
  },
  vivid: {
    light: ["#30599d","#5187e1","#95bcfa","#eeede9","#eea881","#ce6a27","#8e4208"],
    dark: ["#aeccfd","#639af6","#4c6fa8","#3a3a37","#9c5c36","#e27c3d","#f4bd9e"],
  },
  cbsafe: {
    light: ["#245e94","#498dd0","#92bfee","#eeede9","#e2ae85","#be7531","#854a08"],
    dark: ["#a3cffd","#5ca0e4","#48729d","#3a3a37","#92633b","#d28845","#f2bf96"],
  },
};

/** Reserved state colours. Never used for "series 4"; always paired with an icon + label. */
export const STATUS: Record<Mode, StatusColors> = {
  light: { good: "#12ac3e", warning: "#ebbb00", serious: "#fe6909", critical: "#bb001c" },
  dark: { good: "#41cf91", warning: "#ffd335", serious: "#ff8903", critical: "#f9324d" },
};

/**
 * How many leading slots of each palette stay distinguishable when ANY two can be neighbours
 * (scatter, bubble, map, small multiples): all pairs ΔE ≥ 8 under protanopia/deuteranopia and
 * ≥ 15 in normal vision, in both modes. Beyond this, fold to "Other" or facet.
 */
export const ALL_PAIRS_SAFE_SLOTS: Record<string, number> = { gd360: 3, ocean: 3, sunset: 3, forest: 3, berry: 3, slate: 3, vivid: 4, cbsafe: 3 };

export function getPalette(id: string): Palette {
  return PALETTES.find((p) => p.id === id) ?? PALETTES[0];
}

// ───────────────────────────── colour maths ─────────────────────────────

const BAND: Record<Mode, [number, number]> = { light: [0.43, 0.77], dark: [0.48, 0.67] };
const CHROMA_FLOOR = 0.1;
const CVD_TARGET = 8;
const CVD_FLOOR = 6;
const NORMAL_FLOOR = 15;
const CONTRAST_MIN = 3;
/** Non-adjacent slots closer than this (normal vision) are treated as the same colour. */
const FAR_FLOOR = 8;

type V3 = [number, number, number];
export type Cvd = "protan" | "deutan" | "tritan";

// Machado, Oliveira & Fernandes (2009), severity 1.0, applied in linear RGB.
const MACHADO: Record<Cvd, number[]> = {
  protan: [0.152286, 1.052583, -0.204868, 0.114503, 0.786281, 0.099216, -0.003882, -0.048116, 1.051998],
  deutan: [0.367322, 0.860646, -0.227968, 0.280085, 0.672501, 0.047413, -0.01182, 0.04294, 0.968881],
  tritan: [1.255528, -0.076749, -0.178779, -0.078411, 0.930809, 0.147602, 0.004733, 0.691367, 0.3039],
};

/** "#rrggbb" (lower case) from "#rgb", "#rrggbb" or the same without "#"; null if not a colour. */
export function parseHex(input: unknown): string | null {
  if (typeof input !== "string") return null;
  let h = input.trim().replace(/^#/, "");
  if (/^[0-9a-fA-F]{3}$/.test(h)) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  return /^[0-9a-fA-F]{6}$/.test(h) ? "#" + h.toLowerCase() : null;
}

const s2lin = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const lin2s = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const clamp01 = (c: number) => (c < 0 ? 0 : c > 1 ? 1 : c);

function linOf(hex: string): V3 {
  return [0, 2, 4].map((i) => s2lin(parseInt(hex.slice(i + 1, i + 3), 16) / 255)) as V3;
}
function labOfLin([r, g, b]: V3): V3 {
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}
function linOfLab([L, a, b]: V3): V3 {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}
function simulateLin([r, g, b]: V3, kind: Cvd): V3 {
  const M = MACHADO[kind];
  return [clamp01(M[0] * r + M[1] * g + M[2] * b), clamp01(M[3] * r + M[4] * g + M[5] * b), clamp01(M[6] * r + M[7] * g + M[8] * b)];
}

/** OKLCH of a "#rrggbb": L 0–1, C ≥ 0, h in degrees 0–360. */
export function hexToOklch(hex: string): { l: number; c: number; h: number } {
  const [L, a, b] = labOfLin(linOf(hex));
  return { l: L, c: Math.hypot(a, b), h: ((Math.atan2(b, a) * 180) / Math.PI + 360) % 360 };
}
const labOfLch = (l: number, c: number, h: number): V3 => [l, c * Math.cos((h * Math.PI) / 180), c * Math.sin((h * Math.PI) / 180)];
const inGamut = (rgb: V3) => rgb.every((v) => v >= -0.0005 && v <= 1.0005);

/** Largest chroma that stays inside sRGB at this lightness and hue. */
function maxChroma(l: number, h: number): number {
  let lo = 0;
  let hi = 0.4;
  for (let i = 0; i < 18; i++) {
    const mid = (lo + hi) / 2;
    if (inGamut(linOfLab(labOfLch(l, mid, h)))) lo = mid;
    else hi = mid;
  }
  return lo;
}

/** "#rrggbb" for an OKLCH colour; chroma is reduced (hue and lightness kept) if it is out of gamut. */
export function oklchToHex(l: number, c: number, h: number): string {
  let rgb = linOfLab(labOfLch(l, c, h));
  if (!inGamut(rgb)) rgb = linOfLab(labOfLch(l, Math.min(c, maxChroma(l, h)), h));
  return "#" + rgb.map((v) => Math.round(clamp01(lin2s(clamp01(v))) * 255).toString(16).padStart(2, "0")).join("");
}

/** WCAG 2 contrast ratio of two "#rrggbb" colours. */
export function contrast(a: string, b: string): number {
  const y = (hex: string) => {
    const [r, g, bl] = linOf(hex);
    return 0.2126 * r + 0.7152 * g + 0.0722 * bl;
  };
  const ya = y(a);
  const yb = y(b);
  return (Math.max(ya, yb) + 0.05) / (Math.min(ya, yb) + 0.05);
}

/** OKLab ΔE × 100 between two "#rrggbb" colours, optionally under a simulated colour-vision deficiency. */
export function deltaE(a: string, b: string, kind?: Cvd): number {
  const la = labOfLin(kind ? simulateLin(linOf(a), kind) : linOf(a));
  const lb = labOfLin(kind ? simulateLin(linOf(b), kind) : linOf(b));
  return 100 * Math.hypot(la[0] - lb[0], la[1] - lb[1], la[2] - lb[2]);
}

// ───────────────────────────── categorical check ─────────────────────────────

export type CategoricalReport = {
  /** no hard failure (same rule as the reference validator's exit code) */
  ok: boolean;
  /** ok AND no warning: CVD ≥ 8 (not merely ≥ 6) and every slot ≥ 3:1 */
  strict: boolean;
  band: { ok: boolean; offenders: number[] };
  chroma: { ok: boolean; offenders: number[] };
  /** worst pair under protanopia / deuteranopia */
  cvd: { state: "pass" | "floor" | "fail"; worst: number; kind: Cvd; pair: [number, number]; tritan: number };
  /** worst pair in normal vision */
  normal: { ok: boolean; worst: number; pair: [number, number] };
  contrast: { ok: boolean; worst: number; offenders: number[] };
};

/**
 * The computable checks of the dataviz method, on "#rrggbb" colours.
 * `pairs: "adjacent"` (default) is the rule for bars / stacks / lines; `"all"` for scatter / maps.
 */
export function checkCategorical(colors: string[], mode: Mode, opts: { surface?: string; pairs?: "adjacent" | "all" } = {}): CategoricalReport {
  const surface = opts.surface ?? SURFACE[mode];
  const [lo, hi] = BAND[mode];
  const lch = colors.map(hexToOklch);
  const idx = colors.map((_, i) => i);
  const bandOff = idx.filter((i) => lch[i].l < lo || lch[i].l > hi);
  const chromaOff = idx.filter((i) => lch[i].c < CHROMA_FLOOR);
  const pairList: [number, number][] = [];
  for (let i = 0; i < colors.length; i++) {
    if (opts.pairs === "all") for (let j = i + 1; j < colors.length; j++) pairList.push([i, j]);
    else if (i + 1 < colors.length) pairList.push([i, i + 1]);
  }
  let cvdWorst = 99;
  let cvdKind: Cvd = "protan";
  let cvdPair: [number, number] = [0, 0];
  let tritan = 99;
  let norWorst = 99;
  let norPair: [number, number] = [0, 0];
  for (const [i, j] of pairList) {
    for (const kind of ["protan", "deutan"] as Cvd[]) {
      const d = deltaE(colors[i], colors[j], kind);
      if (d < cvdWorst) { cvdWorst = d; cvdKind = kind; cvdPair = [i, j]; }
    }
    tritan = Math.min(tritan, deltaE(colors[i], colors[j], "tritan"));
    const d = deltaE(colors[i], colors[j]);
    if (d < norWorst) { norWorst = d; norPair = [i, j]; }
  }
  const cvdState = cvdWorst >= CVD_TARGET ? "pass" : cvdWorst >= CVD_FLOOR ? "floor" : "fail";
  const ratios = colors.map((c) => contrast(c, surface));
  const contrastOff = idx.filter((i) => ratios[i] < CONTRAST_MIN);
  const ok = !bandOff.length && !chromaOff.length && cvdState !== "fail" && norWorst >= NORMAL_FLOOR;
  return {
    ok,
    strict: ok && cvdState === "pass" && !contrastOff.length,
    band: { ok: !bandOff.length, offenders: bandOff },
    chroma: { ok: !chromaOff.length, offenders: chromaOff },
    cvd: { state: cvdState, worst: cvdWorst, kind: cvdKind, pair: cvdPair, tritan },
    normal: { ok: norWorst >= NORMAL_FLOOR, worst: norWorst, pair: norPair },
    contrast: { ok: !contrastOff.length, worst: ratios.length ? Math.min(...ratios) : 99, offenders: contrastOff },
  };
}

// ───────────────────────────── candidates & search ─────────────────────────────

type Cand = { hex: string; lab: V3; pro: V3; deu: V3; cost: number };

function makeCand(hex: string, cost: number): Cand {
  const lin = linOf(hex);
  return { hex, lab: labOfLin(lin), pro: labOfLin(simulateLin(lin, "protan")), deu: labOfLin(simulateLin(lin, "deutan")), cost };
}
const dist = (a: V3, b: V3) => 100 * Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
const dNormal = (a: Cand, b: Cand) => dist(a.lab, b.lab);
const dCvd = (a: Cand, b: Cand) => Math.min(dist(a.pro, b.pro), dist(a.deu, b.deu));

/** A "#rrggbb" is usable as a categorical slot in this mode: in band, chromatic, ≥ 3:1 on the surface. */
function slotOk(hex: string, mode: Mode): boolean {
  const { l, c } = hexToOklch(hex);
  return l >= BAND[mode][0] && l <= BAND[mode][1] && c >= CHROMA_FLOOR && contrast(hex, SURFACE[mode]) >= CONTRAST_MIN;
}

/**
 * Every usable slot colour of one hue in this mode, on a 0.01 grid of lightness × chroma.
 * Memoised per (mode, rounded hue): the grid is the expensive part of every search below.
 */
const GRID_CACHE: Record<string, string[]> = {};
function hueGrid(h: number, mode: Mode): string[] {
  const key = mode + Math.round(h * 2);
  if (GRID_CACHE[key]) return GRID_CACHE[key];
  const [lo, hi] = BAND[mode];
  const out: string[] = [];
  const seen: Record<string, 1> = {};
  for (let li = Math.round(lo * 100); li <= Math.round(hi * 100); li++) {
    const l = li / 100;
    const cMax = maxChroma(l, h);
    for (let c = CHROMA_FLOOR + 0.004; ; c += 0.01) {
      const cc = Math.min(c, cMax);
      const hex = oklchToHex(l, cc, h);
      if (!seen[hex] && slotOk(hex, mode)) { seen[hex] = 1; out.push(hex); }
      if (cc >= cMax) break;
    }
  }
  return (GRID_CACHE[key] = out);
}

/** Hue to give a colour that has none of its own (black, white, grey): a neutral slate blue. */
const ACHROMATIC_HUE = 255;
const isAchromatic = (hex: string) => hexToOklch(hex).c < 0.02;
const hueOf = (hex: string) => (isAchromatic(hex) ? ACHROMATIC_HUE : hexToOklch(hex).h);

/**
 * Candidates for one colour, nearest to the original first (the original itself if it is usable).
 * `spread` = 0 keeps the hue; > 0 also offers the hue rotated by up to ±spread degrees.
 * A colour with no hue of its own is offered the most muted step of every hue instead — slate
 * first — so that several greys become several distinct muted tones rather than one slate.
 */
function candidatesFor(hex: string, mode: Mode, spread = 0): Cand[] {
  const origin = labOfLin(linOf(hex));
  const out: Cand[] = [];
  if (isAchromatic(hex)) {
    for (let k = 0; k < 12; k++) {
      const h = (ACHROMATIC_HUE + (k % 2 ? 1 : -1) * 30 * Math.ceil(k / 2) + 360) % 360;
      for (const g of hueGrid(h, mode)) {
        if (hexToOklch(g).c > 0.125) continue;
        const c = makeCand(g, 0);
        c.cost = dist(c.lab, origin) + k * 0.8;
        out.push(c);
      }
    }
  } else {
    const h = hueOf(hex);
    const grid = [...hueGrid(h, mode)];
    for (let d = 6; d <= spread; d += 6) grid.push(...hueGrid((h + d) % 360, mode), ...hueGrid((h - d + 360) % 360, mode));
    for (const g of grid) { const c = makeCand(g, 0); c.cost = dist(c.lab, origin); out.push(c); }
    if (slotOk(hex, mode)) out.push(makeCand(hex, -1));
  }
  out.sort((a, b) => a.cost - b.cost);
  return out.filter((c, i) => i === 0 || c.hex !== out[i - 1].hex);
}

/** Candidates for a slot the user left unusable: the default palette's hues, in its own order. */
function standInCandidates(mode: Mode): Cand[] {
  return PALETTES[0][mode].map((hex, i) => makeCand(hex, i));
}

/**
 * Depth-first assignment. Slots are filled in `order`; each takes its cheapest candidate that keeps
 *   neighbouring slots ΔE ≥ 15 (normal) and ≥ 8 (protan/deutan), and every other slot ≥ farFloor.
 * Slots earlier in `order` have priority; a later one backtracks into an earlier one only when stuck.
 */
function assign(cands: Cand[][], order: number[], farFloor: number, budget: number, adjMargin: number): Cand[] | null {
  const n = cands.length;
  const pick: Cand[] = new Array(n);
  const at: number[] = new Array(n).fill(0);
  let d = 0;
  let nodes = 0;
  while (d >= 0 && d < n) {
    const i = order[d];
    let found = false;
    for (let k = at[d]; k < cands[i].length; k++) {
      if (++nodes > budget) return null;
      const c = cands[i][k];
      let good = true;
      for (let e = 0; good && e < d; e++) {
        const j = order[e];
        if (j === i - 1 || j === i + 1) {
          if (dNormal(c, pick[j]) < NORMAL_FLOOR + adjMargin || dCvd(c, pick[j]) < CVD_TARGET + adjMargin) good = false;
        } else if (dNormal(c, pick[j]) < farFloor) good = false;
      }
      if (good) { pick[i] = c; at[d] = k + 1; found = true; break; }
    }
    if (found) { d++; if (d < n) at[d] = 0; }
    else d--;
  }
  return d === n ? pick : null;
}

// ───────────────────────────── custom palettes ─────────────────────────────

export type PaletteIssue = {
  index: number;
  kind: "contrast" | "too_close" | "cvd_close" | "invalid";
  /** index of the other colour, for pair problems */
  with?: number;
  message: string;
};

/**
 * Check up to 10 user-entered brand colours for one mode and return a minimally adjusted list.
 *
 * `issues` describe the INPUT:
 *   invalid    not a hex colour
 *   contrast   under 3:1 against the chart surface, or outside the mode's lightness band
 *   too_close  neighbours under ΔE 15, any two under ΔE 8, or a colour so grey it reads as "Other"
 *   cvd_close  neighbours under ΔE 8 for red-green colour-blind readers
 * `fixed` has one colour per input (first 10), each moved in lightness / chroma only — hue is
 * kept — and only as far as needed, earlier colours taking priority, so the product can say
 * "we adjusted 2 colours so they stay distinguishable". `adjusted` lists the changed indexes.
 *   • A colour with no hue of its own (black, white, grey) becomes a muted tone — slate first.
 *   • An invalid entry is replaced by an unused hue of the default palette; the user's valid
 *     colours are placed first and are never moved to make room for a stand-in.
 *   • Hue is rotated only as a last resort, and by the smallest amount that works: when colours
 *     of one hue cannot be kept apart by lightness and chroma alone (two teals side by side —
 *     the sRGB gamut is thin there — or ten blues).
 * `fixed` always passes checkCategorical, and any two of its colours end up at least ΔE 6 apart
 * (both held over 3,000 fuzzed inputs in palettes.test.mjs).
 */
export function validateCustomPalette(colors: string[], mode: Mode): { ok: boolean; issues: PaletteIssue[]; fixed: string[]; adjusted: number[] } {
  const surface = SURFACE[mode];
  const input = (Array.isArray(colors) ? colors : []).slice(0, 10);
  const parsed = input.map(parseHex);
  const issues: PaletteIssue[] = [];
  const [lo, hi] = BAND[mode];

  parsed.forEach((hex, i) => {
    if (!hex) {
      issues.push({ index: i, kind: "invalid", message: `"${String(input[i])}" is not a hex colour (expected #rrggbb).` });
      return;
    }
    const { l, c } = hexToOklch(hex);
    const ratio = contrast(hex, surface);
    if (ratio < CONTRAST_MIN || l < lo || l > hi) {
      const lightSurface = mode === "light";
      const tooFaint = ratio < CONTRAST_MIN;
      const dir = tooFaint ? (lightSurface ? "too light" : "too dark") : l > hi ? "too light" : "too dark";
      issues.push({
        index: i,
        kind: "contrast",
        message: tooFaint
          ? `${hex} is ${dir} for the ${mode} chart surface (${ratio.toFixed(1)}:1, needs 3:1).`
          : `${hex} is ${dir} to sit alongside the other chart colours on the ${mode} surface.`,
      });
    }
    if (c < CHROMA_FLOOR) {
      issues.push({ index: i, kind: "too_close", message: `${hex} is so muted it reads as grey, like the neutral "Other" colour.` });
    }
  });
  for (let i = 1; i < parsed.length; i++) {
    const a = parsed[i];
    if (!a) continue;
    for (let j = 0; j < i; j++) {
      const b = parsed[j];
      if (!b) continue;
      const adjacent = j === i - 1;
      const dn = deltaE(a, b);
      if (dn < (adjacent ? NORMAL_FLOOR : FAR_FLOOR)) {
        issues.push({
          index: i,
          kind: "too_close",
          with: j,
          message: dn < 0.5 ? `${a} is the same colour as colour ${j + 1}.` : `${a} is hard to tell apart from colour ${j + 1} (${b}).`,
        });
      } else if (adjacent && Math.min(deltaE(a, b, "protan"), deltaE(a, b, "deutan")) < CVD_TARGET) {
        issues.push({ index: i, kind: "cvd_close", with: j, message: `${a} and colour ${j + 1} (${b}) look alike to red-green colour-blind readers.` });
      }
    }
  }

  // Valid colours are placed first (in their own order), stand-ins for invalid entries last.
  const order = [...parsed.keys()].filter((i) => parsed[i]).concat([...parsed.keys()].filter((i) => !parsed[i]));
  const fallback = PALETTES[0][mode];
  let chosen: Cand[] | null = null;
  let cands: Cand[][] = [];
  // The neighbour gates are never relaxed. Keep every hue first, relaxing only the any-two-colours
  // floor (8 → 6); if that is not enough, let hues rotate a little at a time. A floor under 6 is
  // a formality for inputs no rotation can rescue.
  const plan: [number, number][] = [];
  for (const spread of [0, 12, 24, 48, 90]) for (const far of [FAR_FLOOR, 6]) plan.push([spread, far]);
  plan.push([90, 4], [90, 2], [90, 0]);
  let lastSpread = -1;
  for (const [spread, far] of plan) {
    if (spread !== lastSpread) {
      cands = parsed.map((hex) => (hex ? candidatesFor(hex, mode, spread) : standInCandidates(mode)));
      lastSpread = spread;
    }
    chosen = assign(cands, order, far, spread ? 15000 : 30000, 0.05);
    if (chosen) break;
  }
  const fixed = chosen ? chosen.map((c) => c.hex) : cands.map((c, i) => c[0]?.hex ?? fallback[i % fallback.length]);
  const adjusted = fixed.map((hex, i) => (hex === parsed[i] ? -1 : i)).filter((i) => i >= 0);
  return { ok: issues.length === 0, issues, fixed, adjusted };
}

// ───────────────────────────── ramps ─────────────────────────────

/** Lightness at which a colour of this hue/chroma has the given contrast against a surface. */
function lightnessAtContrast(h: number, c: number, surface: string, ratio: number, from: number, to: number): number {
  // contrast is monotone in lightness between `from` (too close to the surface) and `to`
  let a = from;
  let b = to;
  for (let i = 0; i < 20; i++) {
    const mid = (a + b) / 2;
    if (contrast(oklchToHex(mid, Math.min(c, maxChroma(mid, h) * 0.95), h), surface) >= ratio) b = mid;
    else a = mid;
  }
  return b;
}

/**
 * Single-hue 7-step ramp. Index 0 is the lowest value: the step nearest the surface, which
 * still clears 2:1 against it so the faintest mark reads as a mark; index 6 is the highest.
 * Lightness is evenly stepped (≥ 0.06 apart); chroma swells through the middle.
 */
export function sequentialRamp(hue: number, chroma: number, mode: Mode): Hex7 {
  const surface = SURFACE[mode];
  const cPeak = Math.max(0.09, Math.min(0.19, chroma));
  const far = mode === "light" ? 0.3 : 0.9;
  const build = (near: number): string[] => {
    const out: string[] = [];
    for (let i = 0; i < 7; i++) {
      const t = i / 6;
      const l = near + (far - near) * t;
      // chroma swells through the mid-tones and eases off at both ends
      const swell = 0.62 + 0.38 * Math.sin(Math.PI * Math.min(1, t * 1.15 + 0.08));
      out.push(oklchToHex(l, Math.min(cPeak * swell, maxChroma(l, hue) * 0.96), hue));
    }
    return out;
  };
  let near = mode === "light" ? lightnessAtContrast(hue, cPeak * 0.7, surface, 2.05, 0.97, 0.5) : lightnessAtContrast(hue, cPeak * 0.7, surface, 2.05, 0.2, 0.6);
  let out = build(near);
  // the 2:1 floor is checked on the final hex, not the estimate
  for (let guard = 0; guard < 40 && contrast(out[0], surface) < 2.02; guard++) {
    near += mode === "light" ? -0.004 : 0.004;
    out = build(near);
  }
  return out as Hex7;
}

/**
 * Two-hue 7-step diverging ramp around a neutral grey midpoint:
 * [negative ×3 (strongest first), neutral, positive ×3 (strongest last)].
 * Both arms use the same lightness steps, so neither side looks "bigger".
 */
export function divergingRamp(hueNeg: number, huePos: number, chroma: number, mode: Mode): Hex7 {
  const arm = mode === "light" ? [0.47, 0.63, 0.79] : [0.84, 0.69, 0.54]; // strongest → weakest
  const mid = mode === "light" ? "#eeede9" : "#3a3a37";
  const c = Math.max(0.09, Math.min(0.19, chroma));
  const weight = [1, 0.82, 0.55];
  const step = (h: number, k: number) => {
    // hold both arms to the chroma BOTH hues can reach at this lightness, so they stay balanced
    const cap = Math.min(maxChroma(arm[k], hueNeg), maxChroma(arm[k], huePos)) * 0.96;
    return oklchToHex(arm[k], Math.min(c * weight[k], cap), h);
  };
  return [step(hueNeg, 0), step(hueNeg, 1), step(hueNeg, 2), mid, step(huePos, 2), step(huePos, 1), step(huePos, 0)] as Hex7;
}

// ───────────────────────────── brand palettes ─────────────────────────────

/**
 * Build a full chart palette from ONE brand colour. Deterministic.
 *   primary      the brand colour moved (lightness / chroma only, hue kept) into the band where
 *                it works as a chart mark on this mode's surface — unchanged if it already does.
 *   categorical  10 ordered hues: the primary, then nine more spaced 36° around the wheel at the
 *                brand's own chroma, ordered and stepped so neighbours pass every check above.
 *   sequential   a 7-step ramp in the brand hue (index 0 = lowest value).
 * A brand colour with no hue (black, white, grey) yields a slate primary; an unparseable one
 * falls back to the GD360 pine. The result is not steered away from the STATUS colours — a red
 * brand stays red — so keep status marks on their icon + label.
 */
export function paletteFromBrand(hex: string, mode: Mode): { categorical: Hex10; sequential: Hex7; primary: string } {
  const brand = parseHex(hex) ?? "#0f5c46";
  const primary = candidatesFor(brand, mode)[0];
  const h0 = hexToOklch(primary.hex).h;
  const p = hexToOklch(primary.hex);
  // One chroma for the whole family: the brand's, held to a range every hue can reach.
  const cFamily = Math.max(0.11, Math.min(0.15, p.c));
  const [lo, hi] = BAND[mode];
  const lMid = mode === "light" ? 0.57 : 0.6;

  // Nodes of the search: the primary, then for each of the nine other hues its usable steps at the
  // family chroma (every 0.02 of lightness). cost = distance from mid lightness.
  const nodes: Cand[] = [primary];
  const hueOfNode: number[] = [-1];
  for (let k = 1; k < 10; k++) {
    const h = (h0 + 36 * k) % 360;
    const before = nodes.length;
    for (let li = Math.round(lo * 100); li <= Math.round(hi * 100); li += 2) {
      const l = li / 100;
      const cMax = maxChroma(l, h);
      if (cMax < CHROMA_FLOOR + 0.004) continue;
      const stepHex = oklchToHex(l, Math.max(CHROMA_FLOOR + 0.004, Math.min(cFamily, cMax * 0.94)), h);
      if (slotOk(stepHex, mode)) { nodes.push(makeCand(stepHex, Math.abs(l - lMid))); hueOfNode.push(k - 1); }
    }
    if (nodes.length === before) for (const g of hueGrid(h, mode)) { nodes.push(makeCand(g, Math.abs(hexToOklch(g).l - lMid))); hueOfNode.push(k - 1); }
  }
  const n = nodes.length;
  const dn = new Float32Array(n * n);
  const dc = new Float32Array(n * n);
  for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) {
    dn[i * n + j] = dn[j * n + i] = dNormal(nodes[i], nodes[j]);
    dc[i * n + j] = dc[j * n + i] = dCvd(nodes[i], nodes[j]);
  }

  // Order: from each slot, step to the unused hue that differs most from it (and stays clear of
  // every slot already placed). Depth-first, so a dead end backs up instead of failing. The
  // any-two-slots floor starts high and is relaxed only if no ordering exists at that level.
  let best: number[] | null = null;
  for (const far of [12, 10, FAR_FLOOR, 6, 4, 0]) {
    const path: number[] = [0];
    const usedHue: boolean[] = new Array(9).fill(false);
    let budget = 2500;
    const walk = (): boolean => {
      if (path.length === 10) return true;
      const prev = path[path.length - 1];
      const options: { node: number; score: number }[] = [];
      for (let q = 1; q < n; q++) {
        if (usedHue[hueOfNode[q]]) continue;
        const a = dn[prev * n + q];
        const b = dc[prev * n + q];
        if (a < NORMAL_FLOOR + 0.3 || b < CVD_TARGET + 0.3) continue;
        let farMin = 99;
        for (let j = 0; j < path.length - 1; j++) farMin = Math.min(farMin, dn[path[j] * n + q]);
        if (farMin < far) continue;
        // separation from the previous slot, tempered by a pull toward mid lightness
        options.push({ node: q, score: Math.min(a - NORMAL_FLOOR, 2.5 * (b - CVD_TARGET), farMin - far + 6) - 40 * nodes[q].cost });
      }
      options.sort((x, y) => y.score - x.score || x.node - y.node);
      for (const o of options) {
        if (--budget < 0) return false;
        usedHue[hueOfNode[o.node]] = true;
        path.push(o.node);
        if (walk()) return true;
        path.pop();
        usedHue[hueOfNode[o.node]] = false;
      }
      return false;
    };
    if (walk()) { best = path; break; }
  }
  // Unreachable in practice (verified over the whole hue wheel in palettes.test.mjs): fall back to
  // repairing the raw wheel with the same engine validateCustomPalette uses.
  const wheel = [primary.hex];
  for (let k = 0; k < 9; k++) wheel.push(nodes[hueOfNode.indexOf(k)].hex);
  const categorical = (best ? best.map((i) => nodes[i].hex) : validateCustomPalette(wheel, mode).fixed) as Hex10;
  return { categorical, sequential: sequentialRamp(h0, Math.max(p.c, 0.12), mode), primary: primary.hex };
}
